"""add theory model and link examples

Revision ID: 6d2b4a21a1c9
Revises: e4f6a8b0c2d4
Create Date: 2026-09-21 19:51:27.051901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '6d2b4a21a1c9'
down_revision: Union[str, Sequence[str], None] = 'e4f6a8b0c2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('examples', sa.Column('theory_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('examples_level_id_fkey'), 'examples', type_='foreignkey')
    op.create_foreign_key(None, 'examples', 'theory', ['theory_id'], ['id'])
    op.drop_column('examples', 'level_id')
    op.drop_column('levels', 'theory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('theory', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('examples', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'examples', type_='foreignkey')
    op.create_foreign_key(op.f('examples_level_id_fkey'), 'examples', 'levels', ['level_id'], ['id'])
    op.drop_column('examples', 'theory_id')
    op.drop_table('theory')
    # ### end Alembic commands ###
