"""describe your changes

Revision ID: 80dc398d9789
Revises: c854af490069
Create Date: 2026-07-29 12:10:42.713992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '80dc398d9789'
down_revision: Union[str, Sequence[str], None] = 'c854af490069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_problems_created_by_id'), 'problems', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'problems', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_index(op.f('ix_problems_created_by_id'), table_name='problems')
    op.drop_column('problems', 'created_by_id')
    # ### end Alembic commands ###
