"""changes

Revision ID: bf55a994adf9
Revises: 80dc398d9789
Create Date: 2026-07-31 11:23:16.680788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'bf55a994adf9'
down_revision: Union[str, Sequence[str], None] = '80dc398d9789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_problem_assignments',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'class_id')
    )
    op.add_column(
        "problems",
        sa.Column(
            "is_official",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.alter_column(
        "problems",
        "is_official",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'is_official')
    op.drop_table('class_problem_assignments')
    # ### end Alembic commands ###
