"""fix

Revision ID: c854af490069
Revises: 2c15e76ffe34
Create Date: 2026-07-25 11:07:03.141419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'c854af490069'
down_revision: Union[str, Sequence[str], None] = '2c15e76ffe34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('hint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'hint')
    # ### end Alembic commands ###
