"""test models

Revision ID: f9df0b89d0ca
Revises: bf55a994adf9
Create Date: 2026-08-06 13:13:11.937954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'f9df0b89d0ca'
down_revision: Union[str, Sequence[str], None] = 'bf55a994adf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('badge_threshold_percent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('badge_threshold_percent BETWEEN 0 AND 100', name='ck_level_test_badge_threshold'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'version', name='uq_level_test_version')
    )
    op.create_index(op.f('ix_level_tests_level_id'), 'level_tests', ['level_id'], unique=False)
    op.create_index('uq_active_level_test', 'level_tests', ['level_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('test_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('earned_points', sa.Integer(), nullable=True),
    sa.Column('max_points', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('percentage IS NULL OR (percentage >= 0 AND percentage <= 100)', name='ck_test_attempt_percentage'),
    sa.ForeignKeyConstraint(['test_id'], ['level_tests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'user_id', name='uq_test_attempt_user')
    )
    op.create_index(op.f('ix_test_attempts_test_id'), 'test_attempts', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_attempts_user_id'), 'test_attempts', ['user_id'], unique=False)
    op.create_table('test_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("question_type IN ('single_choice', 'short_answer')", name='ck_test_question_type'),
    sa.CheckConstraint('points > 0', name='ck_test_question_points'),
    sa.ForeignKeyConstraint(['test_id'], ['level_tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'order_index', name='uq_test_question_order')
    )
    op.create_index(op.f('ix_test_questions_test_id'), 'test_questions', ['test_id'], unique=False)
    op.create_table('test_question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'order_index', name='uq_test_answer_order')
    )
    op.create_index(op.f('ix_test_question_answers_question_id'), 'test_question_answers', ['question_id'], unique=False)
    op.create_table('test_attempt_answers',
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer_id', sa.Integer(), nullable=True),
    sa.Column('submitted_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.CheckConstraint('points_awarded >= 0', name='ck_test_attempt_answer_points'),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_answer_id'], ['test_question_answers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('attempt_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_attempt_answers')
    op.drop_index(op.f('ix_test_question_answers_question_id'), table_name='test_question_answers')
    op.drop_table('test_question_answers')
    op.drop_index(op.f('ix_test_questions_test_id'), table_name='test_questions')
    op.drop_table('test_questions')
    op.drop_index(op.f('ix_test_attempts_user_id'), table_name='test_attempts')
    op.drop_index(op.f('ix_test_attempts_test_id'), table_name='test_attempts')
    op.drop_table('test_attempts')
    op.drop_index('uq_active_level_test', table_name='level_tests', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_level_tests_level_id'), table_name='level_tests')
    op.drop_table('level_tests')
    # ### end Alembic commands ###
